version: '3.8'

services:
  react-app:
    build:
      context: . # Χρησιμοποιεί τον τρέχοντα φάκελο για το Dockerfile
      dockerfile: Dockerfile
    ports:
      - '3011:80' # Το port 3000 του host συνδέεται με το port 80 του container (Nginx)
    environment:
      REACT_APP_API_URL: http://10.10.20.16:8088/api/v1
    volumes:
      - .:/app # Χρήσιμο για dev περιβάλλοντα αν θες live updates
    restart: always # Αυτόματη επανεκκίνηση αν πέσει το container
